exo1 - JSON & Excel

In [1]:
import pandas as pd

# Lecture d’un fichier JSON classique
df_json = pd.read_json("../data/movies.json")

df_json.head()

# Si le fichier est au format JSON Lines :
# df_json = pd.read_json("../data/movies.json", lines=True)

   id                    title  views
0   1              Data Mining    100
1   2         Machine Learning    150
2   3  Artificial Intelligence    200

 Excel

In [3]:
import pandas as pd

path = "../data/sample.xlsx"

df_excel = pd.read_excel(path)

df_excel.head()

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468

exo2 - Myql

In [1]:
!pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\papa sy\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: pymysql in c:\users\papa sy\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: greenlet>=1 in c:\users\papa sy\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\papa sy\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)

In [7]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:papa1234@localhost/datamining")

query = "SELECT * FROM etudiants WHERE G3 > 15"

df_sql = pd.read_sql(query, engine)

df_sql.head()

Empty DataFrame
Columns: [id, G1, G2, G3]
Index: []

Exo3 - API

In [9]:
pip install requests beautifulsoup4

Requirement already satisfied: requests in c:\users\papa sy\anaconda3\lib\site-packages (2.32.5)
Requirement already satisfied: beautifulsoup4 in c:\users\papa sy\anaconda3\lib\site-packages (4.13.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\papa sy\anaconda3\lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\papa sy\anaconda3\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\papa sy\anaconda3\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\papa sy\anaconda3\lib\site-packages (from requests) (2025.11.12)
Requirement already satisfied: soupsieve>1.2 in c:\users\papa sy\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\papa sy\anaconda3\lib\site-packages (from beautifulsoup4) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import sys
print(sys.executable)

C:\Users\papa sy\anaconda3\python.exe

In [2]:
import requests

response = requests.get("https://example.com")
print(response.status_code)

SSLError: HTTPSConnectionPool(host='example.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1032)')))